#17 added functionality of emailSender and new feture [email confirming]
Reading-room-itm-practice/api pull request #40
Opened 2021-07-08 08:19 UTC by Prestionyk

Should close #17

2021-07-08 08:33 UTC, wikhag requested changes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 200, Message = "Email confirmed succesfully" };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +            return new Response { StatusCode = 400, Message = "Email was'nt able to confirm via this link" };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
>                  return new Response { StatusCode = 422, Message = "User creation failed! Please check user details and try again." };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 201, Message = "Admin user created. Now confirm your email." };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 201, Message = "User created successfully! Now confirm your email." };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
>              return new Response { StatusCode = 422, Message = "Username or password is not correct!" };
Use enum for response codes

2021-07-08 08:33 UTC, wikhag commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                    return new Response { StatusCode = 422, Message = "Invalid username or password!" };
Use enum for response codes

2021-07-08 08:59 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 200, Message = "Email confirmed succesfully" };
Changed in another branch

2021-07-08 08:59 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +            return new Response { StatusCode = 400, Message = "Email was'nt able to confirm via this link" };
Changed in another branch

2021-07-08 08:59 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 201, Message = "Admin user created. Now confirm your email." };
Changed in another branch

2021-07-08 08:59 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                return new Response { StatusCode = 201, Message = "User created successfully! Now confirm your email." };
Changed in another branch

2021-07-08 08:59 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
> +                    return new Response { StatusCode = 422, Message = "Invalid username or password!" };
Changed in another branch

2021-07-08 09:09 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
>                  return new Response { StatusCode = 422, Message = "User creation failed! Please check user details and try again." };
Changed in another branch

2021-07-08 09:09 UTC, Prestionyk commented on WebAPI/Services/User/Authentication/UserAuthenticationService.cs
>              return new Response { StatusCode = 422, Message = "Username or password is not correct!" };
Changed in another branch

2021-07-12 07:25 UTC, Justyn-98 approved these changes

2021-07-12 07:46 UTC, wikhag approved these changes

2021-07-12 07:47 UTC, merged