#16 added reset password feature, rename service and models,
Reading-room-itm-practice/api pull request #53
Opened 2021-07-12 11:46 UTC by Prestionyk

Should close #16

2021-07-13 06:56 UTC, Justyn-98 approved these changes

2021-07-13 08:24 UTC, wikhag requested changes

2021-07-13 08:24 UTC, wikhag commented on Core/DTOs/ResetPasswordDto.cs
> +            ErrorMessage = "Password is not valid (at least one special sign, digit, upper letter and lenght >= 7)")]
You've added this regex in appsettings, read it from those. Also, you might want to add the validationErrorMessage in appsettings too. Or use the Identity password configuration.

2021-07-13 08:24 UTC, wikhag commented on Core/Requests/RegisterRequest.cs
> +            ErrorMessage = "Password is not valid (at least one special sign, digit, upper letter and lenght >= 7)")]
You've added this regex in appsettings, read it from those. Also, you might want to add the validationErrorMessage in appsettings too. Or use the Identity password configuration.

2021-07-13 08:24 UTC, wikhag commented on Core/Services/AuthenticationService.cs
> +            if (model.UserName == null || user == null || !result.Succeeded)
You can shorten it to only check for result.Succeeded, as it will be false when user is null

2021-07-13 08:24 UTC, wikhag commented on Core/Services/AuthenticationService.cs
> +            if (model.UserName == null || user  == null || !result.Succeeded)
You can shorten it to only check for result.Succeeded, as it will be false when user is null

2021-07-13 08:25 UTC, wikhag requested changes

2021-07-13 08:25 UTC, wikhag commented on WebAPI/Controllers/AuthenticateUserController.cs
> +            EmailDto model = new(){Token = token, UserName = username};
missing space between new() {

2021-07-14 11:08 UTC, wikhag approved these changes

2021-07-14 11:10 UTC, merged