#8 reviews
Reading-room-itm-practice/api pull request #60
Opened 2021-07-14 09:08 UTC by Btwol

#8 should close

2021-07-14 10:58 UTC, wikhag requested changes

2021-07-14 10:58 UTC, wikhag commented on Core/Services/ReviewService.cs
> +                var book = _apiDbContext.Books.Include(b => b.Reviews).FirstOrDefault(b => b.Id == bookId);
Don't use dbContext inside services. Create a repository to handle database operations

2021-07-15 11:05 UTC, Justyn-98 approved these changes

2021-07-21 12:02 UTC, wikhag approved these changes

2021-07-21 12:13 UTC, merged