#66 database refactoring
Reading-room-itm-practice/api pull request #78
Opened 2021-07-22 09:27 UTC by Justyn-98

Should close #66

2021-07-22 09:36 UTC, Prestionyk commented
It looks good to me

2021-07-22 10:35 UTC, Prestionyk approved these changes

2021-07-22 13:54 UTC, wikhag requested changes

2021-07-22 13:54 UTC, wikhag commented on Storage/DataAccessLayer/ApiDbContext.cs
> +
Remove this comment

2021-07-26 11:51 UTC, wikhag approved these changes

2021-07-26 11:59 UTC, merged